export const CoursesData=[
    {
        id:1,
        title:"Computer Networking Fundamentals",
        slug:"compute-networking-fundamentals",
        images:"https://broadwayinfosys.com/uploads/courses/81711746535236.webp",
        duration:"",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Er. Sajan Kafle",
    },
    {
        id:2,
        title:"Intro to AI Agents and Agentic AI",
        slug:"ai-agents-and-agentic-ai",
        images:"https://broadwayinfosys.com/uploads/courses/71031747551879.png",
        duration:"",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Kamlesh Sherstha",
    },
    {
        id:3,
        title:"The AI Engineer Course 2025: Complete AI Engineer Bootcamp...",
        slug:"ai-engineer",
        images:"https://broadwayinfosys.com/uploads/courses/76531733822241.jpg",
        duration:"2h",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Pranjana Joshi",
    },
    {
        id:4,
        title:"The Complete Guide To AI Powered Salesforce Development",
        slug:"ai-powered-salesforce-development",
        images:"https://broadwayinfosys.com/uploads/courses/26621747380410.webp",
        duration:"2h",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Madan Adhakari",
    },
    {
        id:5,
        title:"",
        slug:"",
        images:"https://broadwayinfosys.com/uploads/courses/89431733317283.jpg",
        duration:"3h",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Er. Sajan Kafle",
    },
    {
        id:6,
        title:"",
        slug:"",
        images:"https://broadwayinfosys.com/uploads/courses/68281733727891.jpg",
        duration:"3h",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Er. Sajan Kafle",
    },
    {
        id:7,
        title:"",
        slug:"",
        images:"https://broadwayinfosys.com/uploads/courses/68281733727891.jpg",
        duration:"",
        description:"",
        course_type:"",
        rated:"",
        instructor_name:"By Sandesh Bhattrai",
    },
]