import type { Metadata } from "next";
import { Geologica, Google_Sans_Code, Google_Sans_Flex } from "next/font/google";
import "./globals.css";
import LayoutClient from "./LayoutClient";

export const googleSansFlex = Google_Sans_Flex({
  subsets: ["latin"],
  variable: "--font-googleSansFlex",
});

const geologica = Geologica ({
  variable: "--font-geologica",
  subsets: ["latin"],
  fallback: ["serif"],
})

export const googleSansCode = Google_Sans_Code({
  subsets: ["latin"],
  variable: "--font-googleSansCode",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSansFlex.variable} ${googleSansCode.variable} ${geologica.variable} antialiased`}
      >
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
